[context.production.environment]
  REACT_APP_BASE_URL = "https://hidtcop-api.herokuapp.com"

[context.branch-deploy.environment]
  REACT_APP_BASE_URL = "https://hidtcop-staging-api.herokuapp.com"

[context.deploy-preview.environment]
  REACT_APP_BASE_URL = "https://hidtcop-staging-api.herokuapp.com"