# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches:
      - "main"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image local 
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            BASE_URL=http://localhost:8000
            THEME=
            TITLE=HIDTCOP
            TITLE_SHORT=HTP
            TITLE_LONG=HIDTCOP
          tags: |
            jasoniv/hidtcophospitalweblocal:latest

      - name: Build and push docker image dagon lin
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            BASE_URL=http://192.168.100.25:8000
            THEME=#03C0C1
            TITLE=Dagon Lin
            TITLE_SHORT=DGL
            TITLE_LONG=Dagon Lin Hospital
          tags: |
            jasoniv/hidtcophospitalweb:latest

      - name: Build and push docker image kandaw mon
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            BASE_URL=http://localhost:8000
            THEME=
            TITLE=Kan Taw Mon
            TITLE_SHORT=KTM
            TITLE_LONG=Kan Taw Mon Specialist Clinic
          tags: jasoniv/kdm-bill:latest
      - name: Build and push docker image aye thaw dar
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            BASE_URL=http://192.168.100.100:8000
            THEME=
            TITLE=Aye Thaw Dar
            TITLE_SHORT=ATD
            TITLE_LONG=Aye Thaw Dar Specialist Clinic
          tags: jasoniv/atd-bill:latest
